In [2]:
import torch

# Introduction to Tensors

doc: https://pytorch.org/docs/stable/tensors.html

tutorial video: https://www.youtube.com/watch?v=V_xro1bcAuA&t=5143s

web tutorial: https://www.learnpytorch.io/

## Creating Tensors

### Scalar: single value tensor

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# tensor dimension
scalar.ndim

0

In [5]:
# get back scalar tensor to int
scalar.item()

7

### Vector: 1d array of tensor

In [6]:
vector = torch.tensor((7,7))
vector

tensor([7, 7])

In [7]:
# tensor dimension
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
vector[1]

tensor(7)

### Matrix: 2d array

In [10]:
matrix = torch.tensor(((1,2),(3,4)))
matrix

tensor([[1, 2],
        [3, 4]])

In [11]:
# tensor dimension
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
matrix[1]

tensor([3, 4])

In [14]:
matrix[1][0]

tensor(3)

### Tensor: literely tensor, an nd array



In [15]:
tensor = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [7,8,9],
        [4,5,6],
        [1,2,3],
    ]
])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]]])

In [16]:
# tensor dimension
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([2, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
tensor[0][2]

tensor([7, 8, 9])

In [20]:
tensor[0][2][2]

tensor(9)

### Random Tensors

doc: https://pytorch.org/docs/stable/generated/torch.rand.html

In [21]:
random_tensor = torch.rand(3,3,3)
random_tensor

tensor([[[0.4899, 0.9113, 0.3727],
         [0.2720, 0.5754, 0.2171],
         [0.8334, 0.5865, 0.3221]],

        [[0.8781, 0.0755, 0.1931],
         [0.9364, 0.6603, 0.9626],
         [0.1093, 0.5563, 0.7885]],

        [[0.9485, 0.1054, 0.5005],
         [0.1105, 0.4098, 0.3385],
         [0.8790, 0.7521, 0.3861]]])

#### Pseudo-random Tensor

using random seed

In [22]:
DEFINED_RANDOM_SEED_CONSTANT = 334

torch.manual_seed(DEFINED_RANDOM_SEED_CONSTANT)
print(f"pseudorandom:\n{torch.rand(2,2)}") # will be same every time it runs

# using modified seed (will be same in every nth running after above code runned)
print(f"\nnot-setted random seed:\n{torch.rand(2,2)}")

torch.manual_seed(DEFINED_RANDOM_SEED_CONSTANT)
print(f"\npseudorandom:\n{torch.rand(2,2)}") # will be same if setted manual_seed before

pseudorandom:
tensor([[0.9630, 0.6287],
        [0.3162, 0.8529]])

not-setted random seed:
tensor([[0.8125, 0.3667],
        [0.6603, 0.6212]])

pseudorandom:
tensor([[0.9630, 0.6287],
        [0.3162, 0.8529]])


### Zeros and Ones

In [23]:
zeros_tensor = torch.zeros(3,3,3)
zeros_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [24]:
ones_tensor = torch.ones(3,3,3)
ones_tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

### Range/Arange

range is deprecated

In [25]:
one_to_eleven_tensor = torch.arange(1,12)
one_to_eleven_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
two_step_range_tensor = torch.arange(start=0, end=11, step=2)
two_step_range_tensor

tensor([ 0,  2,  4,  6,  8, 10])

In [27]:
one_to_eleven_zeros = torch.zeros_like(one_to_eleven_tensor)
one_to_eleven_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Attributes

Common errors in PyTorch & Deep Learning:


1.   Tensors not on right datatype
2.   Tensors not on right shape
3.   Tensors not on the right device

### Tensor Datatypes



In [28]:
# default tensor datatype
none_datatype_tensor = torch.tensor(
    (1.0,2.0,3.0),
    dtype=None, # datatype of tensor (e.g. float32)
    device=None, # what device is tensor on (e.g cuda or cpu)
    requires_grad=True # wheather or not to track gradients with this tensor operations
                                    )

none_datatype_tensor, none_datatype_tensor.dtype

(tensor([1., 2., 3.], requires_grad=True), torch.float32)

In [29]:
# convert dtype
int_16_tensor = none_datatype_tensor.type(torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([1, 2, 3], dtype=torch.int16), torch.int16)

### Get Tensor Details

In [30]:
some_rand_tensor = torch.rand(3,3,3, dtype=torch.float16)

print(some_rand_tensor, "\n")
print(f"datatype : {some_rand_tensor.dtype}")
print(f"shape    : {some_rand_tensor.size()}") # .size() equals to .shape
print(f"device   : {some_rand_tensor.device}")

tensor([[[0.0444, 0.7935, 0.3096],
         [0.5205, 0.2437, 0.6011],
         [0.0327, 0.0845, 0.9419]],

        [[0.8223, 0.4614, 0.8467],
         [0.9683, 0.5659, 0.6333],
         [0.9731, 0.1372, 0.2607]],

        [[0.9805, 0.7812, 0.2881],
         [0.9570, 0.4341, 0.8174],
         [0.4189, 0.8550, 0.8398]]], dtype=torch.float16) 

datatype : torch.float16
shape    : torch.Size([3, 3, 3])
device   : cpu


## Tensor Manipulation

Tensor manipulations or operations include:
1.  Addition
2.  Subtraction
3.  Element Wise Multiplication
4.  Division
5.  Matrix Multiplication

### Addition

In [31]:
# add by scalar
some_tensor = torch.tensor((1,3,4,6))
some_tensor += 10
some_tensor

tensor([11, 13, 14, 16])

In [32]:
# add by another tensor
tensor1 = torch.tensor((1,2,3))
tensor2 = torch.tensor((3,2,5))

tensor1 + tensor2

''' it would be error if added tensors don't have same shape in same dimension
e.g:

tensor1 = torch.tensor((1,2,3,4))
tensor2 = torch.tensor((3,2,5))

tensor1 + tensor2
'''

" it would be error if added tensors don't have same shape in same dimension\ne.g:\n\ntensor1 = torch.tensor((1,2,3,4))\ntensor2 = torch.tensor((3,2,5))\n\ntensor1 + tensor2\n"

In [33]:
# add by another difference dimension tensor
tensor1 = torch.tensor([(1,2,3),(1,2,3)])
tensor2 = torch.tensor((3,2,5))

tensor1 + tensor2

tensor([[4, 4, 8],
        [4, 4, 8]])

### Subtraction

In [34]:
# subtract by scalar
tensor = torch.tensor((3,4,6))
tensor - 2

tensor([1, 2, 4])

In [35]:
# subtract by another tensor (only works on same shape and dimension)
tensor1 = torch.tensor([
    [1,2,3],
    [3,2,1]
])

tensor2 = torch.tensor([
    [3,2,1],
    [1,3,5]
])

tensor1 - tensor2

tensor([[-2,  0,  2],
        [ 2, -1, -4]])

In [36]:
# add by another difference dimension tensor
tensor1 = torch.tensor([
    [3,2,1],
    [1,3,5]
])

tensor1 - torch.ones(3)

tensor([[2., 1., 0.],
        [0., 2., 4.]])

### Element Wise Multiplication

In [37]:
# multiplicate by scalar
tensor = torch.tensor([
    [3,2,1],
    [1,3,5]
])

tensor * 3

tensor([[ 9,  6,  3],
        [ 3,  9, 15]])

In [38]:
# multiplicate by another tensor (works only on same shape on same dimension)
tensor1 = torch.tensor([
    [3,2,1],
    [1,3,5]
])

tensor2 = torch.tensor([
    [2,2,3],
    [2,3,5]
])

tensor1 * tensor2

tensor([[ 6,  4,  3],
        [ 2,  9, 25]])

In [39]:
# multiplicate by another difference dimension tensor
tensor1 = torch.tensor([
    [3,2,1],
    [1,3,5]
])

tensor2 = torch.tensor([2,2,5])

tensor1 * tensor2

tensor([[ 6,  4,  5],
        [ 2,  6, 25]])

### Division

In [40]:
# divide by scalar
tensor = torch.tensor([
    [3,2,1],
    [1,3,5]
])

tensor / 2

tensor([[1.5000, 1.0000, 0.5000],
        [0.5000, 1.5000, 2.5000]])

In [41]:
# divide by another tensor (only works on same shape and dimension)
tensor1 = torch.tensor([3,2,1])
tensor2 = torch.tensor((3,6,4))

tensor1 / tensor2

tensor([1.0000, 0.3333, 0.2500])

In [42]:
# divide by another difference dimension tensor
tensor1 = torch.tensor([
    [3,2,1],
    [1,3,5]
])

tensor2 = torch.tensor((2,3,4))

tensor1 / tensor2

tensor([[1.5000, 0.6667, 0.2500],
        [0.5000, 1.0000, 1.2500]])

### Matrix Multiplication

To do matrix multiplication, we must perform 3 operation to the matrix:

1. element-wise multiplication
2. sum element from resulted first operation (in same index at last dimension of matrix)
3. do those opeartions and arrange new array/matrix like matrix multiplication should be

`note:` operations 1 and 2 called as **dot-product multiplication**


there are 2 main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must watch:
* `shape(3,2) @ shape(3,2)` won't work
* `shape(3,2) @ shape(2,3)` will work
* `shape(n,m) @ shape(m,n)` will work

2. The resulting matrix has the shape of the outer dimensions:
* `shape(n,m) @ shape(m,n) -> shape(n,n)`
* `shape(n,m) @ shape(m,o) -> shape(n,o)`

In [43]:
matrix1 = torch.tensor([
    [1,2,3],
    [4,5,6]
])

matrix2 = torch.tensor([
    [3,1],
    [2,4],
    [1,5]
])

In [44]:
# matrix multiplication using in-built PyTorch
torch.matmul(matrix1, matrix2)

tensor([[10, 24],
        [28, 54]])

In [45]:
# matrix multiplication using @
matrix1 @ matrix2

tensor([[10, 24],
        [28, 54]])

`note:` currently, matrix multiplication using '**torch.matmul**' and '**@**' with cuda device only support on float dtype (self research).

#### matrix multiplication by hand

In [46]:
# transpose one of the matrix to have same shape
matrix2_transposed = matrix2.T
matrix2_transposed

tensor([[3, 2, 1],
        [1, 4, 5]])

In [47]:
# init array depends on 2nd rule for performing matrix multiplication

# because matrices that will be multiplicated are (2,3) and (3,2), the output must be (2,2)
output_array = [
    [0,0],
    [0,0]
]

In [48]:
# do matrix multiplication
for i in range(matrix1.shape[0]):
  for j in range(matrix2_transposed.shape[0]):
    output_array[i][j] = torch.sum(matrix1[i]*matrix2_transposed[j]).item()

torch.tensor(output_array)

tensor([[10, 24],
        [28, 54]])

## Tensor Basic Statistics

In [49]:
tensor = torch.tensor([
    [3,2],
    [1,5]
])

### MIN MAX

In [50]:
print(f"min value on tensor using torch.min(tensor): {torch.min(tensor)}")
print(f"min value on tensor using tensor.min()     : {tensor.min()}")

min value on tensor using torch.min(tensor): 1
min value on tensor using tensor.min()     : 1


In [51]:
print(f"max value on tensor using torch.max(tensor): {torch.max(tensor)}")
print(f"max value on tensor using tensor.max()     : {tensor.max()}")

max value on tensor using torch.max(tensor): 5
max value on tensor using tensor.max()     : 5


### MEAN MEDIAN

In [52]:
torch.mean(tensor.type(torch.float16)), tensor.type(torch.float16).mean()

(tensor(2.7500, dtype=torch.float16), tensor(2.7500, dtype=torch.float16))

In [53]:
torch.median(tensor), tensor.median()

(tensor(2), tensor(2))

### SUM

In [54]:
torch.sum(tensor), tensor.sum()

(tensor(11), tensor(11))

### Position of MIN and MAX

min -> argmin

max -> argmax

`note:` it use flaten 1d index if tensor has multidimensional shape

In [55]:
tensor.argmin()

tensor(2)

In [56]:
tensor.argmax()

tensor(3)

## Tensor's Shape Manipulation

1. Reshaping - reshape tensor to wanted shape
2. View - return a view of a tensor in certain shape using original allocated tensor's memory
3. Stacking - combine tensors on vertical (vstack) or horizontal (hstack) way
4. Squeeze - removes all 1 dimensions from a tensor
5. Unsqueeze - add a 1 dimension to a tensor
6. Permute - return a view of tensor with dimensions was permuted (swapped) in certain way

In [57]:
tensor = torch.arange(start=0, end= 20, step=2)
tensor, tensor.size()

(tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]), torch.Size([10]))

### Reshape

To do a reshape, PyTorch has in-built function to do a reshape, `torch.reshape(a,b)`. There was a one rule for doing reshape using `torch.reshape(a,b)`. Result of multiplied `a` and `b` must be equals to size of targeted tensor to do a reshape.

In [58]:
tensor_new_shape = tensor.reshape(2,5)
tensor_new_shape, tensor_new_shape.shape

(tensor([[ 0,  2,  4,  6,  8],
         [10, 12, 14, 16, 18]]),
 torch.Size([2, 5]))

In [59]:
tensor_new_shape = tensor.reshape(10,1)
tensor_new_shape, tensor_new_shape.shape

(tensor([[ 0],
         [ 2],
         [ 4],
         [ 6],
         [ 8],
         [10],
         [12],
         [14],
         [16],
         [18]]),
 torch.Size([10, 1]))

### View

Same as reshape do, but the manipulated tensor sharing same memory with original tensor

In [60]:
tensor.view(2,5)

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

### Stacking

In [61]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])

# vstack
print(f"using torch.stack(dim=0):\n{torch.stack([tensor1, tensor2], dim=0)}\n")
print(f"using torch.vstack:\n{torch.vstack([tensor1,tensor2])}\n")

# hstack
print(f"using torch.stack(dim=1):\n{torch.stack([tensor1, tensor2], dim=1)}\n")
print(f"using torch.hstack:\n{torch.hstack([tensor1,tensor2])}")

using torch.stack(dim=0):
tensor([[1, 2, 3],
        [4, 5, 6]])

using torch.vstack:
tensor([[1, 2, 3],
        [4, 5, 6]])

using torch.stack(dim=1):
tensor([[1, 4],
        [2, 5],
        [3, 6]])

using torch.hstack:
tensor([1, 2, 3, 4, 5, 6])


### Squeeze

In [62]:
original_tensor = torch.rand(size=(1,1,3))
original_tensor, original_tensor.shape

(tensor([[[0.4448, 0.7543, 0.0796]]]), torch.Size([1, 1, 3]))

In [63]:
# remove dimensions that's has 1 as their value at shape representation
squeezed_tensor = original_tensor.squeeze()
squeezed_tensor, squeezed_tensor.shape

(tensor([0.4448, 0.7543, 0.0796]), torch.Size([3]))

### Unsqueeze

In [64]:
original_tensor = torch.rand(size=(1,1,3))
original_tensor, original_tensor.shape

(tensor([[[0.9204, 0.9261, 0.8031]]]), torch.Size([1, 1, 3]))

In [65]:
# add a dimension which has 1 as its value at shape representation
unsqueezed_tensor = original_tensor.unsqueeze(dim=3) # dim is required
unsqueezed_tensor, unsqueezed_tensor.shape

(tensor([[[[0.9204],
           [0.9261],
           [0.8031]]]]),
 torch.Size([1, 1, 3, 1]))

### Permute

change order of dimension which resulted as a view

In [66]:
tensor = torch.rand(size=(1,3,2))
tensor, tensor.shape

(tensor([[[0.0336, 0.7121],
          [0.9529, 0.2760],
          [0.4702, 0.1255]]]),
 torch.Size([1, 3, 2]))

In [67]:
tensor_permuted = tensor.permute(1,0,2) # each value represented index of dimension
tensor_permuted, tensor_permuted.shape

(tensor([[[0.0336, 0.7121]],
 
         [[0.9529, 0.2760]],
 
         [[0.4702, 0.1255]]]),
 torch.Size([3, 1, 2]))

## Tensor Indexing

In [68]:
tensor = torch.tensor([
      [
          [1,2,3],
          [4,5,6],
          [7,8,9]
      ],
      [
          [7,8,9],
          [4,5,6],
          [1,2,3],
      ]
    ])

In [69]:
print(tensor[0,0,0])
print(tensor[0][0][0])

tensor(1)
tensor(1)


In [70]:
# get data from all index in 1st dimension, 1st index in 2nd dimension and 2nd index on 3rd dimension
tensor[:,1,2]

tensor([6, 6])

In [71]:
tensor[1][:][0]

tensor([7, 8, 9])

## PyTorch.tensor & NumPy.array

In [72]:
import numpy as np

In [73]:
numpy_array = np.array([1.,2.,3.])
numpy_array,numpy_array.dtype # default dtype of numpy element using 64 bit dtype (e.g, float64 and int64)

(array([1., 2., 3.]), dtype('float64'))

In [74]:
pytorch_tensor = torch.tensor([1.,2.,3.])
pytorch_tensor,pytorch_tensor.dtype # whereas pytorch's tensor using 32 bit dtype at default (e.g. float32 and int32)

(tensor([1., 2., 3.]), torch.float32)

`note:` This should be noted as it will cause an error if there is a difference in data types.

In [75]:
# convert numpy's array into pytorch's tensor
converted_numpy_to_tensor = torch.from_numpy(numpy_array)
converted_numpy_to_tensor, converted_numpy_to_tensor.dtype

(tensor([1., 2., 3.], dtype=torch.float64), torch.float64)

In [76]:
# convert pytorch's tensor into numpy's array
converted_tensor_to_numpy = pytorch_tensor.numpy()
converted_tensor_to_numpy, converted_tensor_to_numpy.dtype

(array([1., 2., 3.], dtype=float32), dtype('float32'))

# PyTorch Devices

devices that can be used to run python program (especially in this google colab) are CPU, GPU and TPU. It can be set at `Runtime > Change runtime type > Runtime type`.

In [77]:
# checking gpu
! nvidia-smi

Tue Jul 11 14:00:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [78]:
# checking gpu using pytorch
torch.cuda.is_available()

True

### An example of GPU usage in PyTorch

In [79]:
DEFINED_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = torch.tensor([1,2,3], device=DEFINED_DEVICE)
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### GPU vs CPU

#### in big dataset

In [80]:
%%time

DEFINED_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DEFINED_RANDOM_SEED1 = 12
DEFINED_RANDOM_SEED2 = 345

torch.manual_seed(DEFINED_RANDOM_SEED1)
tensor1 = torch.rand(1116,2122, device=DEFINED_DEVICE)

torch.manual_seed(DEFINED_RANDOM_SEED2)
tensor2 = torch.rand(2122,2211, device=DEFINED_DEVICE)

tensor1 @ tensor2

CPU times: user 496 ms, sys: 296 ms, total: 793 ms
Wall time: 3.43 s


tensor([[532.5999, 539.2823, 542.0046,  ..., 526.8312, 527.6625, 547.4621],
        [535.0565, 542.3580, 544.7193,  ..., 519.3990, 524.8660, 530.5883],
        [522.6404, 525.5325, 539.9730,  ..., 518.9080, 511.3079, 522.7899],
        ...,
        [520.5353, 524.1520, 534.4307,  ..., 510.2817, 517.1730, 527.5546],
        [537.9145, 527.7098, 548.0740,  ..., 524.7310, 520.6882, 543.8053],
        [528.0515, 530.2881, 529.7807,  ..., 522.6154, 520.9077, 532.8751]],
       device='cuda:0')

In [81]:
%%time

DEFINED_DEVICE = 'cpu'
DEFINED_RANDOM_SEED1 = 12
DEFINED_RANDOM_SEED2 = 345

torch.manual_seed(DEFINED_RANDOM_SEED1)
tensor1 = torch.rand(1116,2122, device=DEFINED_DEVICE)

torch.manual_seed(DEFINED_RANDOM_SEED2)
tensor2 = torch.rand(2122,2211, device=DEFINED_DEVICE)

tensor1 @ tensor2

CPU times: user 194 ms, sys: 17.8 ms, total: 212 ms
Wall time: 227 ms


tensor([[543.3962, 538.3218, 533.0857,  ..., 535.8917, 543.2776, 525.1259],
        [515.7187, 511.0982, 509.8980,  ..., 515.9589, 517.5180, 501.1966],
        [525.0762, 523.1402, 518.7036,  ..., 517.3901, 525.4103, 513.6292],
        ...,
        [541.3095, 534.1326, 536.9413,  ..., 532.9902, 537.2634, 528.1665],
        [528.7742, 532.5107, 531.3000,  ..., 531.7605, 534.1990, 525.4212],
        [530.2505, 524.8204, 516.4583,  ..., 525.9494, 540.7404, 521.4278]])

GPU wins

#### in small dataset

In [82]:
%%time

DEFINED_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DEFINED_RANDOM_SEED1 = 12
DEFINED_RANDOM_SEED2 = 345

torch.manual_seed(DEFINED_RANDOM_SEED1)
tensor1 = torch.rand(16,22, device=DEFINED_DEVICE)

torch.manual_seed(DEFINED_RANDOM_SEED2)
tensor2 = torch.rand(22,11, device=DEFINED_DEVICE)

CPU times: user 214 µs, sys: 0 ns, total: 214 µs
Wall time: 219 µs


In [83]:
%%time

DEFINED_DEVICE = 'cpu'
DEFINED_RANDOM_SEED1 = 12
DEFINED_RANDOM_SEED2 = 345

torch.manual_seed(DEFINED_RANDOM_SEED1)
tensor1 = torch.rand(16,22, device=DEFINED_DEVICE)

torch.manual_seed(DEFINED_RANDOM_SEED2)
tensor2 = torch.rand(22,11, device=DEFINED_DEVICE)

CPU times: user 817 µs, sys: 0 ns, total: 817 µs
Wall time: 703 µs


CPU wins

#### Summary
in big dataset, GPU will be the winner and

# Exercises

## 1. Documentation Reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* [torch.tensor](https://pytorch.org/docs/stable/tensors.html#torch-tensor)
* [torch.cuda](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics)

In [146]:
import torch

## 2. Create a random tensor with shape (7,7)

In [147]:
DEFINED_RANDOM_SEED = 32

torch.manual_seed(DEFINED_RANDOM_SEED)
random_tensor_1 = torch.rand([7,7])

random_tensor_1

tensor([[0.8757, 0.2721, 0.4141, 0.7857, 0.1130, 0.5793, 0.6481],
        [0.0229, 0.5874, 0.3254, 0.9485, 0.5219, 0.8782, 0.7254],
        [0.6929, 0.0259, 0.9319, 0.0913, 0.7177, 0.7271, 0.4967],
        [0.9308, 0.3677, 0.2049, 0.6646, 0.3886, 0.0787, 0.1447],
        [0.1809, 0.6440, 0.1504, 0.7280, 0.8867, 0.2971, 0.7828],
        [0.5105, 0.8187, 0.4370, 0.1878, 0.8781, 0.1925, 0.6161],
        [0.7849, 0.1381, 0.0455, 0.7794, 0.0059, 0.1268, 0.7167]])

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [148]:
random_tensor_2 = torch.rand([1,7])

random_tensor_2

tensor([[0.3324, 0.8529, 0.3920, 0.5805, 0.2238, 0.5989, 0.0382]])

In [149]:
random_tensor_2_transposed = random_tensor_2.T

multiplied_tensor = torch.matmul(random_tensor_1, random_tensor_2_transposed)
multiplied_tensor

tensor([[1.5385],
        [1.8572],
        [1.2857],
        [1.2287],
        [1.4972],
        [1.4836],
        [0.9535]])

## 4. Set the random seed to 0 and do 2 & 3 over again.

will be run on cpu and set manual seed once at begining.

In [150]:
DEFINED_RANDOM_SEED = 0

torch.manual_seed(DEFINED_RANDOM_SEED)

random_tensor_1 = torch.rand([7,7])
random_tensor_2 = torch.rand([1,7])

random_tensor_2_transposed = random_tensor_2.T

multiplied_tensor = torch.matmul(random_tensor_1, random_tensor_2_transposed)

multiplied_tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?

In [151]:
PROCESSING_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors

In [171]:
DEFINED_RANDOM_SEED = 1234

torch.manual_seed(DEFINED_RANDOM_SEED)
random_tensor_1 = torch.rand([2,3], device=PROCESSING_DEVICE)

random_tensor_2 = torch.rand([2,3], device=PROCESSING_DEVICE)

random_tensor_1, random_tensor_2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6

In [157]:
multiplied_tensor = random_tensor_1 @ random_tensor_2.T
multiplied_tensor

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

## 8. Find the maximum and minimum values of the output of 7

In [158]:
multiplied_tensor.max(), multiplied_tensor.min()

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

## 9. Find the maximum and minimum index values of the output of 7

In [159]:
multiplied_tensor.argmax(), multiplied_tensor.argmin()

(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))

## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [165]:
DEFINED_RANDOM_SEED = 7

torch.manual_seed(DEFINED_RANDOM_SEED)
tensor = torch.rand([1,1,1,10])
tensor, tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [167]:
tensor = tensor.squeeze()
tensor, tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))